version: "3.8"

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./thunder/system:/thundersc/thunder/system
      - ./thunder/template:/thundersc/thunder/template
      - ./thundercloud:/thundersc/thundercloud
    environment:
      - HOST_URL=192.168.1.109
      - USER_DB=root
      - PASSWORD_DB=
      - PORT_DB=''
      - DBNAME=mp